name: test_benchmark_cli
description: A starting point for Dart libraries or applications.
version: 1.0.0

executables:
  test_benchmark_cli:

environment:
  sdk: ^3.8.1

dependencies:
  path: ^1.8.3
  args: ^2.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
